# Generated by Django 2.1.5 on 2019-02-23 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallData',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('phone', models.CharField(default=None, max_length=12)),
                ('remarks', models.TextField(default=None)),
                ('recordLink', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('req_id', models.CharField(default=None, max_length=30)),
                ('subject', models.CharField(max_length=100)),
                ('problem_description', models.TextField()),
                ('request_date', models.DateField(auto_now_add=True)),
                ('recording_data_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_ID', models.CharField(default=None, max_length=30, unique=True)),
                ('fname', models.CharField(default=None, max_length=30)),
                ('lname', models.CharField(default=None, max_length=20)),
                ('email', models.CharField(default=None, max_length=30)),
                ('mobile', models.CharField(default=None, max_length=12)),
                ('alternativeMobile', models.CharField(default=None, max_length=12)),
                ('address', models.CharField(default=None, max_length=300)),
                ('pincode', models.CharField(default=None, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empID', models.CharField(default=None, max_length=12, unique=True)),
                ('phone', models.CharField(default=None, max_length=12)),
                ('password', models.CharField(default='password', max_length=20)),
                ('pincode', models.CharField(default='000000', max_length=6)),
                ('email', models.CharField(default='None', max_length=30)),
                ('type', models.CharField(default='tc', max_length=2)),
                ('isActive', models.BooleanField(default=True)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('profilePicture', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loginTime', models.DateTimeField()),
                ('logoutTime', models.DateTimeField()),
                ('employeeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default=None, max_length=100)),
                ('lname', models.CharField(default=None, max_length=100)),
                ('address', models.TextField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone', models.CharField(default=None, max_length=12)),
                ('alternatePhone', models.CharField(default=None, max_length=12)),
                ('purchaseDate', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('pincode', models.CharField(default='000000', max_length=6)),
                ('isContacted', models.CharField(default='no', max_length=3)),
                ('isInterested', models.CharField(default='na', max_length=3)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('product_id', models.CharField(max_length=30, unique=True)),
                ('year', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('category', models.CharField(default='mn', max_length=2)),
                ('features', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='complaints',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Customers'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Employee'),
        ),
        migrations.AddField(
            model_name='calldata',
            name='leadID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Leads'),
        ),
    ]
