# Generated by Django 2.1.7 on 2019-03-27 07:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('callTarget', models.IntegerField()),
                ('commitTarget', models.IntegerField()),
                ('startDate', models.CharField(max_length=10, null=True)),
                ('endDate', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(null=True)),
                ('time', models.CharField(max_length=10, null=True)),
                ('date', models.CharField(max_length=10, null=True)),
                ('noteForAll', models.BooleanField(default=False)),
                ('noteType', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='request_date',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='type',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='year',
            new_name='builtYear',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='id',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='req_id',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='cust_ID',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='id',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='complaints',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='complaints',
            name='appointmentTime',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='complaints',
            name='bookingID',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='complaints',
            name='customerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Leads'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='complaints',
            name='pincode',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='complaints',
            name='severity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='complaints',
            name='technicianID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Employee'),
        ),
        migrations.AddField(
            model_name='customers',
            name='custID',
            field=models.CharField(default=None, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='customers',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Product'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_logo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='empstatus',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='empstatus',
            name='isPause',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empstatus',
            name='pauseTime',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='appointmentDate',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leads',
            name='isCallback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leads',
            name='leadID',
            field=models.CharField(default=None, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='leads',
            name='product',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='source',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to='home/static/images/employee/'),
        ),
        migrations.AlterField(
            model_name='empstatus',
            name='employeeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Employee'),
        ),
        migrations.AlterField(
            model_name='empstatus',
            name='loginTime',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empstatus',
            name='logoutTime',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='address',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='alternatePhone',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='isContacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leads',
            name='isInterested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leads',
            name='phone',
            field=models.CharField(default=None, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='purchaseDate',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='sp', max_length=2),
        ),
        migrations.AddField(
            model_name='notifications',
            name='employeeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Employee'),
        ),
        migrations.AddField(
            model_name='emptarget',
            name='employeeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Employee'),
        ),
    ]
