# Generated by Django 2.1.5 on 2019-02-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190223_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='address',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='alternatePhone',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='phone',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
    ]
