# Generated by Django 2.1.5 on 2019-02-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190223_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empstatus',
            name='loginTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='empstatus',
            name='logoutTime',
            field=models.DateTimeField(null=True),
        ),
    ]
