# Generated by Django 2.1.5 on 2019-02-26 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190223_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='empstatus',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='empstatus',
            name='employeeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Employee'),
        ),
    ]
