# Generated by Django 2.1.5 on 2019-02-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190226_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empstatus',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
