# Generated by Django 2.1.7 on 2019-03-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_emptarget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emptarget',
            old_name='endingDate',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='emptarget',
            old_name='startingDate',
            new_name='startDate',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
