# Generated by Django 2.1.5 on 2019-03-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190301_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profilePicture',
        ),
    ]
