# Generated by Django 2.1.5 on 2019-03-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190302_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('time', models.CharField(max_length=10, null=True)),
                ('date', models.CharField(max_length=10, null=True)),
                ('noteForAll', models.BooleanField(default=False)),
                ('employeeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='complaints',
            name='severity',
            field=models.IntegerField(default=1, max_length=5),
        ),
    ]
