# Generated by Django 2.1.7 on 2019-03-02 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_complaints_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='severity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
