# Generated by Django 2.1.7 on 2019-03-02 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190302_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='severity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
