# Generated by Django 2.1.5 on 2019-03-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190304_1323'),
        ('home', '0018_auto_20190303_2248'),
    ]

    operations = [
    ]
