# Generated by Django 2.1.5 on 2019-03-04 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_merge_20190304_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='noteType',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='severity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
