# Generated by Django 2.1.7 on 2019-03-04 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190304_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='dateAssigned',
            field=models.DateTimeField(default=datetime.date(2019, 3, 4)),
        ),
        migrations.AlterField(
            model_name='leads',
            name='purchaseDate',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
