# Generated by Django 2.1.7 on 2019-03-07 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20190305_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='dateAssigned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
