# Generated by Django 2.1.7 on 2019-03-16 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20190307_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingID', models.CharField(default=None, max_length=10)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('location', models.CharField(default=None, max_length=100)),
                ('address', models.TextField()),
                ('pincode', models.CharField(default='000000', max_length=6)),
                ('complaint', models.TextField()),
                ('appointmentTime', models.DateField()),
                ('customerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Leads')),
                ('technicianID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Employee')),
            ],
        ),
    ]
