# Generated by Django 2.1.7 on 2019-03-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20190316_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='id',
        ),
        migrations.AddField(
            model_name='customers',
            name='cust_ID',
            field=models.CharField(default=None, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
