# Generated by Django 2.1.7 on 2019-03-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20190316_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='cust_ID',
            new_name='custID',
        ),
    ]
